# Generated by Django 4.2.5 on 2023-09-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=50, verbose_name='Наименование услуги')),
                ('img', models.ImageField(upload_to='img-price', verbose_name='Картинка для услуги')),
            ],
            options={
                'verbose_name': 'прайсом',
                'verbose_name_plural': 'Прайс',
            },
        ),
    ]
