# Generated by Django 4.2.5 on 2023-09-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_manicuretype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceService',
            new_name='Service',
        ),
        migrations.AlterModelOptions(
            name='manicuretype',
            options={'verbose_name': 'услугу', 'verbose_name_plural': 'Виды маникюра'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'услугу', 'verbose_name_plural': 'Услуги'},
        ),
    ]
