# Generated by Django 4.2.5 on 2023-09-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_rename_priceservice_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manicuretype',
            options={'verbose_name': 'маникюр', 'verbose_name_plural': 'Виды маникюра'},
        ),
    ]
