# Generated by Django 4.2.5 on 2023-10-04 14:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('manicure_types', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Indefinido'), ('2', 'Temporal'), ('3', 'Formación o Prácticas'), ('4', 'Autónomo o Freelance')], max_length=200)),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
