# Generated by Django 4.2.5 on 2023-10-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0007_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
