# Generated by Django 4.2.5 on 2023-10-04 14:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0008_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('manicure_types', multiselectfield.db.fields.MultiSelectField(choices=[('5', 'Маникюр с покрытием однотонное | Маникюр'), ('7', 'Маникюр укрепление гелем | Маникюр'), ('8', 'Маникюр френч | Маникюр'), ('10', 'Маникюр без покрытия | Маникюр'), ('13', 'Ремонт 1 ногтя | Маникюр'), ('14', 'Укрепление гелем под цвет | Маникюр'), ('15', 'Наращивание - S | Наращивание'), ('16', 'Наращивание - M | Наращивание'), ('17', 'Наращивание - L | Наращивание'), ('18', 'Дизайн ногтей от | Маникюр'), ('20', 'Экстремальное наращивание | Наращивание'), ('21', 'Коррекция наращивания | Наращивание'), ('22', 'Дизайн ногтей от | Наращивание'), ('23', 'SMART - полный с покрытием | Педикюр'), ('24', 'Эстетический педикюр | Педикюр'), ('25', 'Педикюр без покрытия | Педикюр')], max_length=200)),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
