# Generated by Django 4.2.5 on 2023-10-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='price.service', verbose_name='Услуга'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата записи'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='manicure_types',
        ),
        migrations.AddField(
            model_name='order',
            name='manicure_types',
            field=models.ManyToManyField(blank=True, to='price.manicuretype', verbose_name='Виды маникюра'),
        ),
    ]
