# Generated by Django 4.2.5 on 2023-10-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0010_order_service_alter_order_create_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(blank=True, to='price.service', verbose_name='Услуги'),
        ),
    ]
