# Generated by Django 4.2.5 on 2023-10-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0011_remove_order_service_order_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='services',
        ),
    ]
