# Generated by Django 4.2.5 on 2023-10-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0012_remove_order_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(to='price.service', verbose_name='Вид услуги'),
        ),
    ]
