# Generated by Django 4.2.5 on 2023-10-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0013_order_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
