# Generated by Django 4.2.5 on 2023-10-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0014_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('manicure_types_service1', models.ManyToManyField(blank=True, limit_choices_to={'service__name_service': 'Услуга 1'}, related_name='orders_service1', to='price.manicuretype', verbose_name='Виды маникюра (Услуга 1)')),
                ('manicure_types_service2', models.ManyToManyField(blank=True, limit_choices_to={'service__name_service': 'Услуга 2'}, related_name='orders_service2', to='price.manicuretype', verbose_name='Виды маникюра (Услуга 2)')),
                ('manicure_types_service3', models.ManyToManyField(blank=True, limit_choices_to={'service__name_service': 'Услуга 3'}, related_name='orders_service3', to='price.manicuretype', verbose_name='Виды маникюра (Услуга 3)')),
                ('services', models.ManyToManyField(to='price.service', verbose_name='Вид услуги')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
