# Generated by Django 4.2.5 on 2023-10-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0015_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='manicure_types_service1',
            field=models.ManyToManyField(blank=True, limit_choices_to={'service__name_service': 'Маникюр'}, related_name='orders_service1', to='price.manicuretype', verbose_name='Маникюр'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manicure_types_service2',
            field=models.ManyToManyField(blank=True, limit_choices_to={'service__name_service': 'Наращивание'}, related_name='orders_service2', to='price.manicuretype', verbose_name='Наращивание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manicure_types_service3',
            field=models.ManyToManyField(blank=True, limit_choices_to={'service__name_service': 'Педикюр'}, related_name='orders_service3', to='price.manicuretype', verbose_name='Педикюр'),
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(blank=True, to='price.service', verbose_name='Вид услуги'),
        ),
    ]
