# Generated by Django 4.2.5 on 2023-10-13 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0016_alter_order_manicure_types_service1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+7 (XXX) XXX-XX-XX'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона'),
        ),
    ]
