# Generated by Django 4.2.5 on 2023-10-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0017_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=18, verbose_name='Номер телефона'),
        ),
    ]
