# Generated by Django 4.2.5 on 2023-09-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('feedback', models.TextField(verbose_name='Отзыв')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
            ],
            options={
                'verbose_name': 'Что-то твое на русском на родном',
                'verbose_name_plural': 'Что-то твое на русском на родном',
            },
        ),
    ]
