# Generated by Django 4.2.5 on 2023-09-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='images-slider', verbose_name='Картинка')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'картинка',
                'verbose_name_plural': 'Картинки для портфолио',
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'пользователя с отзывом', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
