# Generated by Django 4.2.5 on 2023-09-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_portfolio_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'картинку', 'verbose_name_plural': 'Картинки для портфолио'},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img',
            field=models.FileField(blank=True, upload_to='images-slider', verbose_name='Картинка'),
        ),
    ]
