# Generated by Django 4.2.5 on 2023-09-29 16:22

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_portfolio_options_alter_portfolio_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='img',
            field=models.FileField(blank=True, upload_to='images-slider', validators=[main.models.Portfolio.validate_image_extension], verbose_name='Картинка'),
        ),
    ]
