# Generated by Django 4.2.5 on 2023-10-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование курса')),
                ('img', models.ImageField(upload_to='img-courses', verbose_name='Картинка для курса')),
                ('mini_description', models.TextField(verbose_name='Мини описание курса')),
                ('count_group', models.CharField(max_length=30, verbose_name='Количество людей в группе')),
                ('time_course', models.CharField(max_length=30, verbose_name='Длительность курса')),
                ('certificate', models.CharField(max_length=30, verbose_name='Документ об окончании курса')),
                ('price', models.IntegerField(verbose_name='Стоимость курса')),
                ('description', models.TextField(verbose_name='Полное описание курса')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
