# Generated by Django 4.2.5 on 2023-10-13 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=18, verbose_name='Номер телефона')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_write', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'запись на курс',
                'verbose_name_plural': 'Клиенты курса',
            },
        ),
    ]
